# Test your FastAPI endpoints

GET http://localhost:8050/api/scraper/hello-world
Accept: application/json

###

GET http://localhost:8050/api/scraper/config/pipeline-types
Accept: application/json

###

GET http://localhost:8050/api/scraper/config/pipeline-types/scraper_main
Accept: application/json

###