from pipelineFramework import Configuration, LocalisationString

TECHNOLOGIES_CONFIG = Configuration(
    "technologies",
    LocalisationString("Technologies", "Technologies"),
    [
        {
            "label": "Fortschrittliche Materialien inkl. Nanotechnologien",
            "short": "",
            "style": {"color": "#70A357", "accent": "#BBD9AD"},
            "technologies": [
                {"label": "Nanomaterialien", "short": ""},
                {"label": "Biomaterialien", "short": ""},
                {"label": "Metamaterialien", "short": ""},
                {"label": "Energiematerialien", "short": ""},
                {"label": "Additive-Fertigungsmaterialien", "short": ""},
                {"label": "Fortschrittliche keramische Materialien", "short": ""},
                {"label": "Funktionale Beschichtungen und Oberfl\u00e4chenbehandlung", "short": ""},
            ],
        },
        {
            "label": "K\u00fcnstliche Intelligenz, Big Data, Digitale und Informatiosntechnologien",
            "short": "",
            "style": {"color": "#575AA3", "accent": "#9A9CD5"},
            "technologies": [
                {"label": "Maschinelles Lernen", "short": ""},
                {"label": "Neuronale Netze", "short": ""},
                {"label": "Nat\u00fcrliche Sprachverarbeitung (NLP)", "short": ""},
                {"label": "Datenanalyse-Tools", "short": ""},
                {"label": "Datenvisualisierung", "short": ""},
                {"label": "Datenbanken", "short": ""},
                {"label": "Data Mining", "short": ""},
                {"label": "Cloud-Computing", "short": ""},
                {"label": "Internet of Things (IoT)", "short": ""},
                {"label": "Blockchain-Technologie", "short": ""},
                {"label": "Cybersecurity-Technologien", "short": ""},
            ],
        },
        {
            "label": "Quantentechnologie und Photonik",
            "short": "",
            "style": {"color": "#988030", "accent": "#DBCD9F"},
            "technologies": [
                {"label": "Quantum Computing", "short": ""},
                {"label": "Quantum Communication", "short": ""},
                {"label": "Quantum Meterology", "short": ""},
                {"label": "Quantum Sensing", "short": ""},
                {"label": "Quantum Simulation", "short": ""},
            ],
        },
        {
            "label": "Fortschrittliche Mikroelektronik/Halbleiter",
            "short": "",
            "style": {"color": "#8C57A3", "accent": "#BD90D1"},
            "technologies": [
                {"label": "Prozessoren", "short": ""},
                {"label": "Hochfrequenzchips", "short": ""},
                {"label": "Nanoelektronik & integrierte Schaltungen", "short": ""},
                {"label": "Halbleiterfertigungsanlagen", "short": ""},
                {"label": "Weltraumtaugliche Halbleitertechnologien", "short": ""},
            ],
        },
        {
            "label": "Fortschrittliche Produktionstechnologien und Robotik, fortschrittliche Sensortechnologie",
            "short": "",
            "style": {"color": "#5797A3", "accent": "#93D2DE"},
            "technologies": [
                {"label": "Additive Fertigung", "short": ""},
                {"label": "Industrie 4.0 Konzepte", "short": ""},
                {"label": "KI-gest\u00fctzte Fertigung", "short": ""},
                {"label": "Kollaborative Roboter", "short": ""},
                {"label": "Pr\u00e4dikative Wartung", "short": ""},
                {"label": "Chemische Sensoren", "short": ""},
                {"label": "Biologische Sensoren", "short": ""},
                {"label": "Strahlungssensoren", "short": ""},
                {"label": "Magnetometer", "short": ""},
                {"label": "Magnetfeldgradientenmesser", "short": ""},
                {"label": "Elektro-optische Sensoren", "short": ""},
                {"label": "Unterwasser-Elektrosensoren", "short": ""},
                {"label": "Gravimeter", "short": ""},
                {"label": "Gravitationswellendetektoren", "short": ""},
            ],
        },
        {
            "label": "Life Science Technologien",
            "short": "",
            "style": {"color": "#A36657", "accent": "#DDACA0"},
            "technologies": [
                {"label": "Nanobiotechnologie", "short": ""},
                {"label": "Agrarbiotechnologie", "short": ""},
                {"label": "Synthetische Biologie", "short": ""},
                {"label": "Regenerative Medizin", "short": ""},
                {"label": "Arzneimittel f\u00fcr Neuartige Therapien", "short": ""},
                {"label": "Impfstoffe", "short": ""},
                {"label": "Biologicals und Biosimilars", "short": ""},
                {"label": "Bioinformatik", "short": ""},
                {"label": "Bioprozesstechnologie", "short": ""},
                {"label": "Biooptik und bildgebende Verfahren", "short": ""},
                {"label": "Neue Gentechnik", "short": ""},
            ],
        },
        {
            "label": "Energieerzeugung und -speicherung",
            "short": "",
            "style": {"color": "#A3578F", "accent": "#DEACD1"},
            "technologies": [
                {"label": "Fortschrittliche Batterien und Energiespeicherung", "short": ""},
                {"label": "Intelligente Netztechnologien", "short": ""},
                {"label": "Alternative Kraftstoffe", "short": ""},
                {
                    "label": "Erneuerbare Energietechnologien (inkl. Solartechnologien, Windkrafttechnologien, W\u00e4rmepumpen, Elektrolyseure, Brennstoffzellen etc.",
                    "short": "",
                },
            ],
        },
        {
            "label": "Nachhaltige Technologien: Kreislaufwirtschaft, Geb\u00e4ude, Abfall / Wasser",
            "short": "",
            "style": {"color": "#604D33", "accent": "#8D7D68"},
            "technologies": [
                {
                    "label": "Recycling Technologien zur R\u00fcckf\u00fchrung von Materialien in den Stoffkreislauf",
                    "short": "",
                },
                {"label": "Saubere und nachhaltige Technologien im Geb\u00e4udebereich", "short": ""},
                {"label": "Saubere und nachhaltige Technologien im Abfall / Abwasser-Bereich", "short": ""},
                {"label": "Kohlenstoffabscheidung- und -speicherung", "short": ""},
            ],
        },
    ],
)
