from pipelineFramework import Configuration, LocalisationString

TECHNOLOGIES_CONFIG = Configuration(
    "technologies",
    LocalisationString("Technologies", "Technologies"),
    [
        {
            "label": "Künstliche Intelligenz und Dateninnovation",
            "short": "",
            "style": {"color": "#CD6A42", "accent": "#d19a84"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Maschinelles Lernen",
                    "short": "",
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Deep Learning",
                    "short": "",
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Generative KI",
                    "short": "",
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Large Language Models",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Natural Language Processing",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Computer Vision",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Reinforcement Learning",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Hybrid AI",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Erklärbare und Vertrauenswürdige KI",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Edge AI",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Federated Learning",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Privacy-Preserving AI",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "MLOps",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Datenräume",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Data Governance",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Datenqualität",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "KI-basierte Qualitätskontrolle",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Prozessoptimierung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Prognosemodelle und Automatisierung komplexer Aufgaben",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Chips, Elektronische Komponenten und Systeme",
            "short": "",
            "style": {"color": "#A52932", "accent": "#c77d82"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Halbleiter",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Mikroelektronik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Nanoelektronik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Integrierte Schaltungen und Chipdesign",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Sensorik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "MEMS",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Leistungselektronik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Analog-/Mixed-Signal-Chips",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "RF-/HF-Komponenten",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Embedded Systems",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Secure Connectivity",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Advanced Packaging",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "System-on-Chip",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "System-in-Packag",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Photonische integrierte Schaltungen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Quantenchips",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Pilotlinien und Halbleiter-Testinfrastruktur",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Fortgeschrittene Produktionstechnologien und Robotik",
            "short": "",
            "style": {"color": "#752347", "accent": "#ab6885"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Additive Fertigung / 3D-Druck",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Industrielle und Kollaborative Robotik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Autonome Produktionssysteme",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Automatisierung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Cyber-Physische Produktionssysteme",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Industrie 4.0 und digitale Zwillinge",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Manufacturing-X / Produktionsdatenräume",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Prozesssimulation",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Inline-Messtechnik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Predictive Maintenanc",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Zerstörungsfreie Prüfung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Flexible Fertigung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Rekonfigurierbare Produktion",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Pilotfabriken",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Quantentechnologie und Photonik",
            "short": "",
            "style": {"color": "#59437C", "accent": "#9684b3"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Quantencomputing",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Quantensimulation",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Quantenkommunikation",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Quantum Key Distribution",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Quantensensorik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Quantenmetrologie",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Quantenchips und Quantenalgorithmen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Photonik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Laser",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Optische Sensorik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Spektroskopie",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Optische Messtechnik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Lidar",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Photonische integrierte Schaltungen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Optische Kommunikation",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Bildgebung und photonikbasierte Fertigung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Fortgeschrittene Werkstoffe (Advanced Materials)",
            "short": "",
            "style": {"color": "#2E5793", "accent": "#8fa6c9"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Ultraleichte Verbundwerkstoffe",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Advanced Composites",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Hochleistungslegierungen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Selbstheilende Polymere",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Biobasierte und Multifunktionale Biomaterialien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Funktionale Materialien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Nanomaterialien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Intelligente Materialien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Oberflächen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Beschichtungen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Grenzflächen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Batteriematerialien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Wasserstoffmaterialien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Materialien für Energieumwandlung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Recyclingfähige Werkstoffe",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Safe-and-Sustainable-by-Design",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Life-Sciences & Biotech",
            "short": "",
            "style": {"color": "#4C8090", "accent": "#82a9b5"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Arzneimittelentwicklung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Biologika",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Impfstoffe",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Diagnostika",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Medizinprodukte",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Klinische Studien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Biomarker",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Genomik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Proteomik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Omics-Technologien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Bioinformatik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Personalisierte Medizin",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Zell- und Gentherapien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "CRISPR / Gene Editing",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Synthetische Biologie",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Industrielle Biotechnologie",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Fermentation",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Bioprozessentwicklung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Biobasierte Materialien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Digitale Gesundheit",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Energie- und Umwelttechnologien",
            "short": "",
            "style": {"color": "#5B869F", "accent": "#93b4c7"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Erneuerbare Energien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Energieumwandlung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Batteriespeicher",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Thermische Speicher",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Wasserstoff",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Grüne Gase",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Power-to-X",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Smart Grids",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Netztechnologien und Energieeffizienz",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Wärmepumpen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Industrielle Abwärme",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Klimaneutrale Prozesswärme",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "CO2-Management",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "CCU/CCS",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Kreislaufwirtschaft",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Recycling",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Ressourceneffizienz",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Umweltmonitoring",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Wasser-, Abfall- und Luftreinhaltung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Mobilitätstechnologien",
            "short": "",
            "style": {"color": "#616A1E", "accent": "#abb374"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Emissionsfreie Antriebe",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Elektromobilität",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Brennstoffzellen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Wasserstoffmobilität",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Lade- und Betankungsinfrastruktur",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Leichtbau",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Batterieintegration und Fahrzeugsoftware",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Automatisierte Fahrzeuge",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Vernetzte Verkehrssysteme",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "C-ITS",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "V2X-Kommunikation",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Mobility-as-a-Service",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Digitale Mobilitätsdienste",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Verkehrssteuerung",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Bahntechnologien und Logistiksystem",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
        {
            "label": "Weltraum- und Luftfahrttechnologien",
            "short": None,
            "style": {"color": "#E2AD34", "accent": "#e8ce90"},
            "programmes": [],
            "technologies": [
                {
                    "label": "Satellitentechnologien",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Erdbeobachtung / Copernicus",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Wetter- und Klimamonitoring",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Navigation / GNSS",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Satellitenkommunikation",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Raumfahrtkomponenten",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Weltraumelektronik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "On-board-Systeme",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Sensorik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Satellitendatenanalyse",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Weltraumwissenschaft",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Sicherheits-/Resilienzbezogene Anwendungen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Avionik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Nachhaltige Luftfahrt",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "SAF",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Wasserstoff in der Luftfahrt",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Aerodynamik",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Leichte Strukturen",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
                {
                    "label": "Flugverkehrsmanagement",
                    "short": None,
                    "style": {"color": None, "accent": None},
                    "programmes": [],
                    "searchTerms": [],
                },
            ],
        },
    ],
)
